version: '3.9'

services:

  my-django-docker-app:
    image: kuntalsamantadocker/kuntal-docker-django:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 9000:8000
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://my-django-docker-app:9000"]
    #   interval: 10s
    #   timeout: 10s
    #   start_period: 10s
    #   retries: 3
    depends_on:
      - run-migrate
      - my-unit-test
      - redis
      - celery
      - celery-beat
    deploy:
      replicas: 2

  run-migrate:
    image: kuntalsamantadocker/kuntal-docker-django:latest
    command: python manage.py migrate
  
  my-unit-test:
    image: kuntalsamantadocker/kuntal-docker-django:latest
    command: python manage.py test

  redis:
    image: redis:alpine

  celery:
    image: kuntalsamantadocker/kuntal-docker-django:latest
    command: celery -A core worker -l info

  celery-beat:
    image: kuntalsamantadocker/kuntal-docker-django:latest
    command: celery -A core beat -l info
