version: '3.3'

services:
  psql-db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


# postgres_data this volumes is not exist, below will create a new
volumes:
  postgres_data:

