# from a particular compose file
version: "3.9"

services:

  # 1
  webapp:
    build:
      context: ./dir/my-folder
      dockerfile: Dockerfile-alternate

  # 2
  web:
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
  db:
    image: postgres:latest
